name: 'Update case counts data'

on:
  # Scheduled updates are disabled. Reenable by uncommenting this block.
  # schedule:
  #  - cron: '0 8 * * *'

  repository_dispatch:
    types: update-case-counts-data

  workflow_dispatch:


jobs:
  update-case-counts-data:
    runs-on: ubuntu-20.04

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: update-case-counts-data
        run: |
          set -x

          git config --global user.name neherlab-bot
          git config --global user.email neherlab-bot@users.noreply.github.com

          PATH="$HOME/.local/bin:$PWD/node_modules/.bin:$PATH"

          python3 -m pip install --upgrade pip setuptools pipenv

          yarn install
          yarn schema:totypes

          cd data
          pipenv sync

          pipenv run python generate_data.py --fetch
          git add case-counts/*tsv
          git commit -m "update case count tsv files"

          pipenv run python generate_data.py --output-cases ../src/assets/data/caseCounts.json
          git add ../src/assets/data/caseCounts.json
          git commit -m "update case count json"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.NEHERLAB_BOT_GITHUB_TOKEN }}
          author: 'neherlab-bot <neherlab-bot@users.noreply.github.com>'
          committer: 'neherlab-bot <neherlab-bot@users.noreply.github.com>'
          branch: 'chore/update-case-counts'
          commit-message: 'update case counts data'
          title: '[bot] Update case counts data'
          body: |
            Updates case counts data:
            - update case count tsv files
            - update case count json

            Generated by Github Action: [${{github.run_id}}](https://github.com/neherlab/covid19_scenarios/actions/runs/${{github.run_id}}?check_suite_focus=true)

            See also: [Recent Github Actions](https://github.com/neherlab/covid19_scenarios/actions?query=workflow%3A%22Update%20case%20counts%20data%22)

            Update can be re-triggered manually in Github Actions UI or with [GitHub CLI](https://github.com/cli/cli):
            ```
            gh workflow run 'Update case counts data'
            ```

          labels: |
            s:data
            bot
          delete-branch: true

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
